// This code conforms with the UFC specification version 2016.1.0
// and was automatically generated by FFC version 2016.1.0.
// 
// This code was generated with the following parameters:
// 
//   convert_exceptions_to_warnings: False
//   cpp_optimize:                   True
//   cpp_optimize_flags:             '-O2'
//   epsilon:                        1e-14
//   error_control:                  False
//   form_postfix:                   False
//   format:                         'ufc'
//   no-evaluate_basis_derivatives:  True
//   optimize:                       False
//   precision:                      15
//   quadrature_degree:              -1
//   quadrature_rule:                'auto'
//   representation:                 'auto'
//   split:                          False

#ifndef __FFC_FORM_9606004CB983BE1A9D3B8EDB030F4F6957BBAF9F_H
#define __FFC_FORM_9606004CB983BE1A9D3B8EDB030F4F6957BBAF9F_H
#include <stdexcept>
#include <ufc.h>

extern "C" ufc::finite_element * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_finite_element_0();


extern "C" ufc::finite_element * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_finite_element_1();


extern "C" ufc::finite_element * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_finite_element_2();


extern "C" ufc::finite_element * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_finite_element_3();


extern "C" ufc::finite_element * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_finite_element_4();


extern "C" ufc::finite_element * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_finite_element_5();


extern "C" ufc::dofmap * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_dofmap_0();


extern "C" ufc::dofmap * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_dofmap_1();


extern "C" ufc::dofmap * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_dofmap_2();


extern "C" ufc::dofmap * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_dofmap_3();


extern "C" ufc::dofmap * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_dofmap_4();


extern "C" ufc::dofmap * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_dofmap_5();




extern "C" ufc::form * create_ffc_form_9606004cb983be1a9d3b8edb030f4f6957bbaf9f_form_0();

#endif
