// This code conforms with the UFC specification version 2016.1.0
// and was automatically generated by FFC version 2016.1.0.
// 
// This code was generated with the following parameters:
// 
//   convert_exceptions_to_warnings: False
//   cpp_optimize:                   True
//   cpp_optimize_flags:             '-O2'
//   epsilon:                        1e-14
//   error_control:                  False
//   form_postfix:                   False
//   format:                         'ufc'
//   no-evaluate_basis_derivatives:  True
//   optimize:                       False
//   precision:                      15
//   quadrature_degree:              -1
//   quadrature_rule:                'auto'
//   representation:                 'auto'
//   split:                          False

#ifndef __FFC_FORM_2A9DA807058BF1C5E8DEEEA3849E9C8C8545B8D0_H
#define __FFC_FORM_2A9DA807058BF1C5E8DEEEA3849E9C8C8545B8D0_H
#include <stdexcept>
#include <ufc.h>

extern "C" ufc::finite_element * create_ffc_form_2a9da807058bf1c5e8deeea3849e9c8c8545b8d0_finite_element_0();


extern "C" ufc::finite_element * create_ffc_form_2a9da807058bf1c5e8deeea3849e9c8c8545b8d0_finite_element_1();


extern "C" ufc::finite_element * create_ffc_form_2a9da807058bf1c5e8deeea3849e9c8c8545b8d0_finite_element_2();


extern "C" ufc::dofmap * create_ffc_form_2a9da807058bf1c5e8deeea3849e9c8c8545b8d0_dofmap_0();


extern "C" ufc::dofmap * create_ffc_form_2a9da807058bf1c5e8deeea3849e9c8c8545b8d0_dofmap_1();


extern "C" ufc::dofmap * create_ffc_form_2a9da807058bf1c5e8deeea3849e9c8c8545b8d0_dofmap_2();



extern "C" ufc::form * create_ffc_form_2a9da807058bf1c5e8deeea3849e9c8c8545b8d0_form_0();

#endif
