// This code conforms with the UFC specification version 2016.1.0
// and was automatically generated by FFC version 2016.1.0.
// 
// This code was generated with the following parameters:
// 
//   convert_exceptions_to_warnings: False
//   cpp_optimize:                   True
//   cpp_optimize_flags:             '-O2'
//   epsilon:                        1e-14
//   error_control:                  False
//   form_postfix:                   False
//   format:                         'ufc'
//   no-evaluate_basis_derivatives:  True
//   optimize:                       False
//   precision:                      15
//   quadrature_degree:              4
//   quadrature_rule:                'auto'
//   representation:                 'auto'
//   split:                          False

#ifndef __FFC_FORM_E397C7B6A6388A9ED0B31AB39E87CBBE31F895DF_H
#define __FFC_FORM_E397C7B6A6388A9ED0B31AB39E87CBBE31F895DF_H
#include <stdexcept>
#include <ufc.h>

extern "C" ufc::finite_element * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_finite_element_0();


extern "C" ufc::finite_element * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_finite_element_1();


extern "C" ufc::finite_element * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_finite_element_2();


extern "C" ufc::finite_element * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_finite_element_3();


extern "C" ufc::finite_element * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_finite_element_4();


extern "C" ufc::finite_element * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_finite_element_5();


extern "C" ufc::dofmap * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_dofmap_0();


extern "C" ufc::dofmap * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_dofmap_1();


extern "C" ufc::dofmap * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_dofmap_2();


extern "C" ufc::dofmap * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_dofmap_3();


extern "C" ufc::dofmap * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_dofmap_4();


extern "C" ufc::dofmap * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_dofmap_5();




extern "C" ufc::form * create_ffc_form_e397c7b6a6388a9ed0b31ab39e87cbbe31f895df_form_0();

#endif
